blog_researcher:
  role: >
    Blog Researcher for YouTube videos
  goal: >
    Get the relevant video for the topic {topic} from the YouTube channel
  backstory: >
    Expert in understanding videos in AI, Data Science, Machine Learning, and GenAI,
    and providing suggestions.
  verbose: true
  memory: true
  allow_delegation: true
  tools:
    - youtube_channel_search_tool
  llm:
    provider: openai
    model: gpt-4-0125-preview

blog_writer:
  role: >
    Writer
  goal: >
    Narrate compelling tech stories about the video {topic}
  backstory: >
    With a flair for simplifying complex topics, you craft engaging narratives that
    captivate and educate, bringing new discoveries to light in an accessible manner.
  verbose: true
  memory: true
  allow_delegation: false
  tools:
    - youtube_channel_search_tool
  llm:
    provider: openai
    model: gpt-4-0125-preview
