research_task:
  description: >
    Identify the video {topic}. Get detailed information about the video from the YouTube channel.
  expected_output: >
    A comprehensive 3-paragraph long report based on the {topic} of video content.
  tools:
    - youtube_channel_search_tool
  agent: blog_researcher

write_task:
  description: >
    Get the info from the YouTube channel on the topic {topic}.
  expected_output: >
    Summarize the info from the YouTube channel video on the topic {topic} and create the content for the blog.
  tools:
    - youtube_channel_search_tool
  agent: blog_writer
  async_execution: false
  output_file: new-blog-md
